import type { ClothingClassification, SourceType } from "@/lib/types";

export type DemoClothingInput = ClothingClassification & {
  imageUrl: string;
  sourceType: SourceType;
  sourceUrl: string | null;
  originalClassification: null;
};

export const demoWardrobeItems: DemoClothingInput[] = [
  {
    name: "Beyaz basic tişört",
    mainCategory: "upper",
    subCategory: "t-shirt",
    colors: ["white"],
    styleTags: ["casual", "basic", "summer"],
    seasonTags: ["spring", "summer", "all_season"],
    formality: "casual",
    aiDescription: "Sıcak ve ılık havalarda alt parçalarla kolay eşleşen nötr üst.",
    confidence: 0.92,
    imageUrl: "/wardrobe/categories/tshirt/tshirt.png",
    sourceType: "image_url",
    sourceUrl: null,
    originalClassification: null,
  },
  {
    name: "Krem kazak",
    mainCategory: "upper",
    subCategory: "sweater",
    colors: ["cream", "beige"],
    styleTags: ["minimal", "smart_casual", "comfortable"],
    seasonTags: ["autumn", "winter"],
    formality: "smart_casual",
    aiDescription: "Serin havalarda sıcak tutan, nötr renkli üst parça.",
    confidence: 0.9,
    imageUrl: "/wardrobe/categories/sweater/sweater.png",
    sourceType: "image_url",
    sourceUrl: null,
    originalClassification: null,
  },
  {
    name: "Koyu jean pantolon",
    mainCategory: "lower",
    subCategory: "jeans",
    colors: ["blue", "navy"],
    styleTags: ["casual", "streetwear", "basic"],
    seasonTags: ["all_season"],
    formality: "casual",
    aiDescription: "Günlük kombinlerde üst parçalarla rahat eşleşen alt parça.",
    confidence: 0.88,
    imageUrl: "/placeholder-clothing.svg",
    sourceType: "image_url",
    sourceUrl: null,
    originalClassification: null,
  },
  {
    name: "Siyah kumaş pantolon",
    mainCategory: "lower",
    subCategory: "trousers",
    colors: ["black"],
    styleTags: ["minimal", "formal", "smart_casual"],
    seasonTags: ["all_season"],
    formality: "smart_casual",
    aiDescription: "Ofis ve akşam kombinlerinde kullanılabilecek sade alt parça.",
    confidence: 0.86,
    imageUrl: "/placeholder-clothing.svg",
    sourceType: "image_url",
    sourceUrl: null,
    originalClassification: null,
  },
  {
    name: "Kahverengi ceket",
    mainCategory: "outerwear",
    subCategory: "jacket",
    colors: ["brown"],
    styleTags: ["classic", "smart_casual"],
    seasonTags: ["autumn", "winter"],
    formality: "smart_casual",
    aiDescription: "Serin ve yağışlı günlerde kombini tamamlayan dış katman.",
    confidence: 0.91,
    imageUrl: "/wardrobe/categories/jacket/jacket.png",
    sourceType: "image_url",
    sourceUrl: null,
    originalClassification: null,
  },
  {
    name: "Beyaz sneaker",
    mainCategory: "shoes",
    subCategory: "sneakers",
    colors: ["white"],
    styleTags: ["casual", "sporty", "comfortable"],
    seasonTags: ["spring", "summer", "all_season"],
    formality: "casual",
    aiDescription: "Günlük kullanım için rahat ve nötr ayakkabı.",
    confidence: 0.87,
    imageUrl: "/placeholder-clothing.svg",
    sourceType: "image_url",
    sourceUrl: null,
    originalClassification: null,
  },
  {
    name: "Siyah bot",
    mainCategory: "shoes",
    subCategory: "boots",
    colors: ["black"],
    styleTags: ["classic", "smart_casual"],
    seasonTags: ["autumn", "winter"],
    formality: "smart_casual",
    aiDescription: "Soğuk veya yağışlı havalarda daha uygun ayakkabı seçimi.",
    confidence: 0.85,
    imageUrl: "/placeholder-clothing.svg",
    sourceType: "image_url",
    sourceUrl: null,
    originalClassification: null,
  },
];
